use crate::error::Error;
use crate::import::{fnt, fnt_ttf};
use image::{Rgba, RgbaImage};
use serde_json::json;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
/// Output file paths generated by bitmap font export.
pub struct BitmapExportPaths {
    pub png_path: PathBuf,
    pub json_path: PathBuf,
    pub bmfont_path: PathBuf,
}

fn ensure_parent_dir(path: &Path) -> Result<(), Error> {
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent).map_err(|e| Error::File {
            path: parent.to_path_buf(),
            message: format!("failed to create directory: {e}"),
        })?;
    }
    Ok(())
}

fn paired_output_paths(output: &Path) -> (PathBuf, PathBuf) {
    let ext = output
        .extension()
        .and_then(|e| e.to_str())
        .map(|s| s.to_ascii_lowercase());

    match ext.as_deref() {
        Some("png") => (output.to_path_buf(), output.with_extension("json")),
        Some("json") => (output.with_extension("png"), output.to_path_buf()),
        Some(_) => (output.with_extension("png"), output.with_extension("json")),
        None => {
            let mut png = output.to_path_buf();
            png.set_extension("png");
            let mut json_path = output.to_path_buf();
            json_path.set_extension("json");
            (png, json_path)
        }
    }
}

fn write_bmfont_text(
    face_name: &str,
    png_path: &Path,
    fnt_path: &Path,
    line_height: u16,
    sheet_w: u32,
    sheet_h: u32,
    glyph_entries: &[serde_json::Value],
) -> Result<(), Error> {
    let page_file = png_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("atlas.png");

    let mut text = String::new();
    text.push_str(&format!(
        "info face=\"{face_name}\" size={line_height} bold=0 italic=0 charset=\"\" unicode=1 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=1,1 outline=0\n"
    ));
    text.push_str(&format!(
        "common lineHeight={line_height} base={line_height} scaleW={sheet_w} scaleH={sheet_h} pages=1 packed=0 alphaChnl=0 redChnl=0 greenChnl=0 blueChnl=0\n"
    ));
    text.push_str(&format!("page id=0 file=\"{page_file}\"\n"));
    text.push_str("chars count=");
    text.push_str(&glyph_entries.len().to_string());
    text.push('\n');

    for glyph in glyph_entries {
        let codepoint = glyph.get("codepoint").and_then(|v| v.as_u64()).unwrap_or(0);
        let x = glyph.get("sheet_x").and_then(|v| v.as_u64()).unwrap_or(0);
        let y = glyph.get("sheet_y").and_then(|v| v.as_u64()).unwrap_or(0);
        let width = glyph.get("width").and_then(|v| v.as_u64()).unwrap_or(0);
        let height = glyph.get("height").and_then(|v| v.as_u64()).unwrap_or(0);
        let xoffset = glyph
            .get("offset_left")
            .and_then(|v| v.as_i64())
            .unwrap_or(0);
        let yoffset = glyph
            .get("offset_top")
            .and_then(|v| v.as_i64())
            .unwrap_or(0);
        let xadvance = width.saturating_add(1);

        text.push_str(&format!(
            "char id={codepoint} x={x} y={y} width={width} height={height} xoffset={xoffset} yoffset={yoffset} xadvance={xadvance} page=0 chnl=15\n"
        ));
    }

    std::fs::write(fnt_path, text)?;
    Ok(())
}

/// Converts an input FNT file to a TTF file at `output_path`.
pub fn export_fnt_ttf(input_path: &Path, output_path: &Path) -> Result<(), Error> {
    let bytes = std::fs::read(input_path)?;
    let parsed = fnt::parse_fnt(&bytes)?;

    let family_name = input_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("RedguardFnt");

    let ttf_bytes = fnt_ttf::build_ttf_from_fnt(&parsed, family_name)?;

    ensure_parent_dir(output_path)?;
    std::fs::write(output_path, ttf_bytes)?;

    Ok(())
}

/// Exports an input FNT file as atlas PNG plus JSON and BMFont metadata.
pub fn export_fnt_bitmap(
    input_path: &Path,
    output_path: &Path,
) -> Result<BitmapExportPaths, Error> {
    let bytes = std::fs::read(input_path)?;
    let fnt = fnt::parse_fnt(&bytes)?;

    let glyph_count = fnt.glyphs.len() as u32;
    let max_width = fnt
        .glyphs
        .iter()
        .map(|g| u32::from(g.width))
        .max()
        .unwrap_or(1);
    let max_height = fnt
        .glyphs
        .iter()
        .map(|g| u32::from(g.height))
        .max()
        .unwrap_or(1);

    let cell_w = max_width.saturating_add(2);
    let cell_h = max_height.saturating_add(2);

    let mut cols = 1_u32;
    while cols.saturating_mul(cols) < glyph_count.max(1) {
        cols = cols.saturating_add(1);
    }
    let rows = glyph_count.max(1).div_ceil(cols);

    let sheet_w = (cols.saturating_mul(cell_w)).max(1);
    let sheet_h = (rows.saturating_mul(cell_h)).max(1);
    let mut image = RgbaImage::new(sheet_w, sheet_h);

    for px in image.pixels_mut() {
        *px = Rgba([0, 0, 0, 0]);
    }

    let mut glyph_meta = Vec::with_capacity(fnt.glyphs.len());

    for (idx, glyph) in fnt.glyphs.iter().enumerate() {
        let i = idx as u32;
        let col = i % cols;
        let row = i / cols;
        let origin_x = col.saturating_mul(cell_w).saturating_add(1);
        let origin_y = row.saturating_mul(cell_h).saturating_add(1);

        let codepoint = u32::from(fnt.header.character_start).saturating_add(i);
        let ch = char::from_u32(codepoint).unwrap_or('?');

        for y in 0..u32::from(glyph.height) {
            for x in 0..u32::from(glyph.width) {
                let pix_idx = (y as usize)
                    .saturating_mul(usize::from(glyph.width))
                    .saturating_add(x as usize);
                let pal_idx = *glyph.pixels.get(pix_idx).unwrap_or(&0) as usize;
                let color = fnt
                    .palette
                    .colors
                    .get(pal_idx)
                    .copied()
                    .unwrap_or([0_u8, 0_u8, 0_u8]);
                let rgba = if pal_idx == 0 {
                    [0, 0, 0, 0]
                } else {
                    [
                        color[0].saturating_mul(4),
                        color[1].saturating_mul(4),
                        color[2].saturating_mul(4),
                        255,
                    ]
                };

                image.put_pixel(origin_x + x, origin_y + y, Rgba(rgba));
            }
        }

        glyph_meta.push(json!({
            "index": idx,
            "codepoint": codepoint,
            "char": ch.to_string(),
            "enabled": glyph.enabled,
            "offset_left": glyph.offset_left,
            "offset_top": glyph.offset_top,
            "width": glyph.width,
            "height": glyph.height,
            "sheet_x": origin_x,
            "sheet_y": origin_y
        }));
    }

    let (png_path, json_path) = paired_output_paths(output_path);
    let bmfont_path = json_path.with_extension("fnt");
    ensure_parent_dir(&png_path)?;
    ensure_parent_dir(&json_path)?;
    ensure_parent_dir(&bmfont_path)?;
    image
        .save(&png_path)
        .map_err(|e| Error::Conversion(e.to_string()))?;

    let face_name = input_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("RedguardFnt");
    write_bmfont_text(
        face_name,
        &png_path,
        &bmfont_path,
        fnt.header.line_height,
        sheet_w,
        sheet_h,
        &glyph_meta,
    )?;

    let metadata = json!({
        "format": "redguard-fnt-export-v1",
        "source_file": input_path,
        "chunk_order": fnt.chunk_order,
        "has_rdat": fnt.rdat.is_some(),
        "trailing_padding_bytes": fnt.trailing_padding.len(),
        "palette_tag": String::from_utf8_lossy(&fnt.palette.tag).to_string(),
        "palette_size": fnt.palette.colors.len(),
        "sheet": {
            "path": png_path.file_name().and_then(|n| n.to_str()).unwrap_or(""),
            "width": sheet_w,
            "height": sheet_h,
            "cell_width": cell_w,
            "cell_height": cell_h,
            "columns": cols,
            "rows": rows
        },
        "header": {
            "description_text": fnt.header.description_text,
            "description_raw_hex": fnt
                .header
                .description_raw
                .iter()
                .map(|b| format!("{b:02x}"))
                .collect::<String>(),
            "unknown_24": fnt.header.unknown_24,
            "has_rdat": fnt.header.has_rdat,
            "unknown_28": fnt.header.unknown_28,
            "unknown_2a": fnt.header.unknown_2a,
            "unknown_2c": fnt.header.unknown_2c,
            "max_width": fnt.header.max_width,
            "line_height": fnt.header.line_height,
            "character_start": fnt.header.character_start,
            "character_count": fnt.header.character_count,
            "unknown_36": fnt.header.unknown_36,
            "unknown_38": fnt.header.unknown_38,
            "has_palette": fnt.header.has_palette
        },
        "glyphs": glyph_meta
    });

    let metadata_json = serde_json::to_string_pretty(&metadata)?;
    std::fs::write(&json_path, metadata_json)?;

    Ok(BitmapExportPaths {
        png_path,
        json_path,
        bmfont_path,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    #[ignore]
    fn manual_export_redsel_ttf_to_out() {
        let input = Path::new("fonts/REDSEL.FNT");
        let output = Path::new("out/REDSEL.ttf");
        assert!(
            input.exists(),
            "expected sample font at {}",
            input.display()
        );
        export_fnt_ttf(input, output).expect("manual REDSEL export should succeed");
        assert!(output.exists(), "expected output at {}", output.display());
    }
}
